# Generated by Django 4.0.3 on 2022-03-29 00:39

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trip_driver_bus_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 29, 0, 39, 6, 24370, tzinfo=utc))]),
        ),
    ]
